// Generated by CoffeeScript 1.10.0
(function() {
  var base, base1, data, root;

  if ((base = Array.prototype).first == null) {
    base.first = function(n) {
      if (n != null) {
        return this.slice(0, Math.max(0, n));
      } else {
        return this[0];
      }
    };
  }

  if ((base1 = Array.prototype).last == null) {
    base1.last = function(n) {
      if (n != null) {
        return this.slice(Math.max(this.length - n, 0));
      } else {
        return this[this.length - 1];
      }
    };
  }

  root = typeof GLOBAL !== "undefined" && GLOBAL !== null ? GLOBAL : this;

  data = {
    target_element: "",
    circle_diameter: "",
    sides: "",
    start_at_x: "",
    start_at_y: "",
    radius: "",
    inner_color: "white",
    line_color: "black",
    line_width: 1
  };

  root.polygen = function(input_data) {
    var $ctx, angle, html, i, j, key, ref, target_name, value;
    for (key in input_data) {
      value = input_data[key];
      data[key] = value;
    }
    if (data.start_at_x === "") {
      data.start_at_x = data.circle_diameter / 2;
    }
    if (data.start_at_y === "") {
      data.start_at_y = data.circle_diameter / 2;
    }
    if (data.radius === "") {
      data.radius = data.circle_diameter / 2 - 10;
    }
    target_name = data.target_element.split("#").last() + "_polygen";
    html = "<canvas class='polygen' id='" + target_name + "' width='" + data.circle_diameter + "'height='" + data.circle_diameter + "'></canvas>";
    $(data.target_element).append(html);
    if (data.sides > 2) {
      $ctx = $("#" + target_name)[0].getContext("2d");
      angle = Math.PI * 2 / data.sides;
      $ctx.save();
      $ctx.fillStyle = data.inner_color;
      $ctx.strokeStyle = data.line_color;
      $ctx.lineWidth = data.line_width;
      $ctx.translate(data.start_at_x, data.start_at_y);
      $ctx.moveTo(0, -parseInt(data.radius));
      $ctx.beginPath();
      for (i = j = 0, ref = data.sides; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        $ctx.rotate(angle);
        $ctx.lineTo(0, -parseInt(data.radius));
      }
      $ctx.closePath();
      $ctx.stroke();
      $ctx.fill();
      return $ctx.restore();
    } else {
      return console.log("a polygon should has sides more than 3 sides");
    }
  };

}).call(this);
